CREATE TABLE affirmation(
  id int    PRIMARY KEY    NOT NULL,
  content        TEXT      NOT NULL,
  author         TEXT      NOT NULL
);

INSERT INTO affirmation(id, content, author) VALUES
(0, 'Akceptuję cuda i wszelkie pozytywne zmiany w całym swoim życiu','afirmacje.pl'),
(1, 'Akceptuję doskonałe zdrowie i wygląd swojego ciała','afirmacje.pl'),
(2, 'Akceptuję i doceniam wysoki potencjał mojego ciała','afirmacje.pl'),
(3, 'Akceptuję i szanuję swoje seksualne ciało','afirmacje.pl'),
(4, 'Akceptuję seks w swoim życiu','afirmacje.pl'),
(5, 'Akceptuję siebie jako osobę szczupłą i zgrabną','afirmacje.pl'),
(6, 'Akceptuję swoje ciało, doznania i potrzeby cielesne','afirmacje.pl'),
(7, 'Akceptuję swoją seksualność','afirmacje.pl'),
(8, 'Akceptuję to miejsce w swoim życiu, w którym się obecnie znajduję i dostrzegam jakie mam twórcze możliwości będąc właśnie w tym momencie życia','afirmacje.pl'),
(9, 'Akceptuję to, że inni cierpią, chorują i męczą się z własnego wyboru','afirmacje.pl'),
(10, 'Akceptuję to, że moje życie ma sens','afirmacje.pl'),
(11, 'Akceptuję to, że potrzebuję pieniędzy aby żyć łatwo i wygodnie','afirmacje.pl'),
(12, 'Akceptuję to, że wolna wola z bożym wsparciem ma większą moc sprawczą niż najsilniejsze wzorce','afirmacje.pl'),
(13, 'Akceptuję w sobie harmonię miłości, mądrości i mocy','afirmacje.pl'),
(14, 'Akceptuję zdrowie i pełnię sił witalnych w swoim ciele i życiu','afirmacje.pl'),
(15, 'Akceptuję świat takim, jaki jest','afirmacje.pl'),
(16, 'Akceptuję, szanuję i lubię siebie i swoje ciało bez względu na to, jak wyglądam','afirmacje.pl'),
(17, 'Bawię się razem z Bogiem na trzeźwo i przytomnie w pracy, twórczości, związku miłości i w seksie','afirmacje.pl'),
(18, 'Bezwarunkowe szczęście, radość i miłość są dla mnie w pełni bezpieczne i naturalne','afirmacje.pl'),
(19, 'Biorę odpowiedzialność za siebie i swój twórczy potencjał','afirmacje.pl'),
(20, 'Biorę udział w coraz ciekawszych, twórczych przedsięwzięciach, które przynoszą mi coraz większe dochody','afirmacje.pl'),
(21, 'Bogactwo i obfitość są moim naturalnym stanem','afirmacje.pl'),
(22, 'Boska miłość wypełnia i uzdrawia całe moje ciało','afirmacje.pl'),
(23, 'Boska obfitość i bogactwo urzeczywistniają się na wszystkich poziomach mojego istnienia','afirmacje.pl'),
(24, 'Boska ochrona i prowadzenie są silniejsze od wszystkich obaw i leków','afirmacje.pl'),
(25, 'Boży plan dla mnie, oraz cały potencjał mojej duszy realizuję bezpiecznie, radośnie, łatwo, dla mojego najwyższego dobra','afirmacje.pl'),
(26, 'Bycie sobą i nowe doświadczenia są dla mnie bezpieczne, ciekawe i przyjemne','afirmacje.pl'),
(27, 'Bóg Mnie kocha bez względu na to, co uczyniłem','afirmacje.pl'),
(28, 'Bóg daje mi wszystko, co mi potrzebne do twórczego życia i rozwoju','afirmacje.pl'),
(29, 'Bóg jest jedyną siłą twórczą we mnie, dlatego światłość i miłość mogą zawsze przepływać i wyrażać się przeze mnie bez najmniejszego oporu','afirmacje.pl'),
(30, 'Bóg już teraz zaspokaja wszystkie moje potrzeby','afirmacje.pl'),
(31, 'Bóg który mieszka we mnie ma niepodzielną władzę nade mną i jest jedynym źródłem informacji, na które się otwieram','afirmacje.pl'),
(32, 'Bóg mnie chroni, dlatego tworzę pracę swojego życia w sposób bezpieczny i korzystny dla mnie','afirmacje.pl'),
(33, 'Bóg mnie prowadzi i wspiera w realizacji moich marzeń i w przejawianiu moich talentów','afirmacje.pl'),
(34, 'Bóg mnie wspiera zawsze i wszędzie, poprzez czystą miłość, moc i mądrość','afirmacje.pl'),
(35, 'Bóg nieustannie wspiera mnie w nauce i rozwoju','afirmacje.pl'),
(36, 'Bóg ochrania mnie i prowadzi zapewniając mi bezpieczną przestrzeń do przejawiania się, swobodnego rozwoju, pracy i życia','afirmacje.pl'),
(37, 'Bóg pomaga mi również poprzez innych ludzi, poprzez sytuacje życiowe, w jakich się znajduję','afirmacje.pl'),
(38, 'Bóg porządkuje całe moje życie, a ja z ufnością zgadzam się na to','afirmacje.pl'),
(39, 'Bóg pozwala mi doświadczać przyjemności i miłości w seksie','afirmacje.pl'),
(40, 'Bóg pozwala mi na samodzielność, Bóg aprobuje moje niezależne decyzje','afirmacje.pl'),
(41, 'Bóg prowadzi mnie do pełnego uzdrowienia','afirmacje.pl'),
(42, 'Bóg stworzył mnie abym radośnie przejawiał mój twórczy potencjał','afirmacje.pl'),
(43, 'Bóg stworzył mnie jako istotę czystą i niewinną i to jest moja prawdziwa natura','afirmacje.pl'),
(44, 'Bóg stworzył mnie na swoje podobieństwo, jako istotę twórczą i spełnioną','afirmacje.pl'),
(45, 'Bóg stworzył mnie niewinnego i wolnego od odpowiedzialności za innych','afirmacje.pl'),
(46, 'Bóg uwalnia mnie od wszelkich lęków i oporów przed doskonałym seksem','afirmacje.pl'),
(47, 'Bóg wspiera mnie w przejawianiu pełni swojej doskonałości','afirmacje.pl'),
(48, 'Bóg wspiera mnie w realizacji moich pomysłów','afirmacje.pl'),
(49, 'Bóg wspiera moją twórczą postawę, Bóg zapewnia mi wszelkie środki do realizacji mojego twórczego celu','afirmacje.pl'),
(50, 'Bóg zapewnia mi radość, miłość, bogactwo i spełnienie','afirmacje.pl'),
(51, 'Bóg zapewnia mi wszelkie środki potrzebne do realizacji pracy mojego życia, a ja chętnie z nich korzystam','afirmacje.pl'),
(52, 'Bóg zapewnia mi wszystkie środki potrzebne do realizacji moich celów','afirmacje.pl'),
(53, 'Bóg zawsze kocha mnie i akceptuje to, co robię','afirmacje.pl'),
(54, 'Bóg zawsze mi pomaga w realizacji moich twórczych planów, ponieważ w ten sposób zbliżam się do Niego, ponieważ odkrywam doskonałość w sobie','afirmacje.pl'),
(55, 'Bóg zawsze wspiera mnie we wszystkim, co dla mnie ważne','afirmacje.pl'),
(56, 'Bóg zawsze wynagradza mnie, nawet gdy popełniam błędy','afirmacje.pl'),
(57, 'Będąc sobą jestem bezpieczny dla siebie i innych','afirmacje.pl'),
(58, 'Całe moje ciało istnieje dla mojej radości, wygody i przyjemności','afirmacje.pl'),
(59, 'Całe moje ciało służy doświadczaniu miłości i przyjemności w pracy, związkach i w seksie','afirmacje.pl'),
(60, 'Całe moje ciało wibruje czystą energią Miłości','afirmacje.pl'),
(61, 'Całkowicie akceptuję swoją czystość i niewinność','afirmacje.pl'),
(62, 'Całkowite zaufanie i pojednanie z Bogiem jest dla mnie bezpieczne i korzystne','afirmacje.pl'),
(63, 'Cenię moje twórcze pomysły, ufam stale wzrastającej zdolności tworzenia obfitości poprzez przejawianie ich','afirmacje.pl'),
(64, 'Chcę, mogę i potrafię być w pełni zadowolony z siebie, swojej pracy, swoich związków, całego swojego życia','afirmacje.pl'),
(65, 'Chętnie przyjmuję pieniądze i prezenty od ludzi, którzy chętnie mi je dają','afirmacje.pl'),
(66, 'Cokolwiek dzieje się we mnie i wokół mnie, jest dla mnie całkowicie bezpieczne','afirmacje.pl'),
(67, 'Czerpiąc ze Źródła mam nieograniczony twórczy potencjał','afirmacje.pl'),
(68, 'Czując i postrzegając w sposób pełny jestem całkowicie bezpieczny','afirmacje.pl'),
(69, 'Czuję się bezpiecznie i swobodnie w swoim ciele','afirmacje.pl'),
(70, 'Czuję się bezpiecznie, niewinnie i w porządku, kiedy realizuję swoje cele i osiągam sukcesy','afirmacje.pl'),
(71, 'Czuję się cenny i wartościowy, dlatego pozwalam sobie być sobą i swobodnie wyrażać siebie niezależnie od tego, co inni o mnie myślą','afirmacje.pl'),
(72, 'Czuję się niewinny i w porządku, kiedy odmawiam','afirmacje.pl'),
(73, 'Czuję się odpowiedzialny za własne życie i własne wybory, akceptuje to, że moje życie, to mój wybór','afirmacje.pl'),
(74, 'Czuję się pewnie, bezpiecznie i niewinnie, dlatego pozwalam sobie być sobą i swobodnie wyrażać siebie w obecności każdej osoby','afirmacje.pl'),
(75, 'Czuję, jak każdego dnia moje ciało jest coraz zdrowsze','afirmacje.pl'),
(76, 'Daję sobie pozwolenie by mieć to, czego chcę, moja twórcza postawa prowadzi mnie do celu','afirmacje.pl'),
(77, 'Daję sobie prawo do sukcesu w życiu','afirmacje.pl'),
(78, 'Daję sobie uwagę i czystą miłość w obecności innych, bo jestem godny czystej miłości, szacunku i akceptacji taki, jaki jestem','afirmacje.pl'),
(79, 'Daję sobie uwagę i czystą miłość, szczęście, radość i przyjemność, bo jestem godny tego jaki jestem','afirmacje.pl'),
(80, 'Daję sobie uwagę zawsze i wszędzie i w obecności każdej osoby, bo pozwalam sobie i innym w pełni szanować, akceptować i doceniać siebie','afirmacje.pl'),
(81, 'Decyduję się na urzeczywistnienie moich talentów w całej krasie, świat mnie w tym wspiera','afirmacje.pl'),
(82, 'Dla Boga wszystko jest możliwe, nawet to, żeby było możliwe dla mnie','afirmacje.pl'),
(83, 'Dla mnie trzeźwość i przytomność jest bezpieczna, atrakcyjna, przyjemna i korzystna','afirmacje.pl'),
(84, 'Dla mnie życie jest łatwe, lekkie, przyjemne, pełne ciepła i miłości','afirmacje.pl'),
(85, 'Doceniam boski potencjał w sobie i w innych ludziach','afirmacje.pl'),
(86, 'Doceniam siebie, dlatego pozwalam innym doceniać mnie i to jak wyrażam moje talenty','afirmacje.pl'),
(87, 'Doceniam siebie, więc potrafię się cieszyć z moich sukcesów','afirmacje.pl'),
(88, 'Doceniam swoją pracę, to co umiem i to co robię','afirmacje.pl'),
(89, 'Doceniam swój twórczy potencjał, pozwalam innym by robili to samo','afirmacje.pl'),
(90, 'Doceniam wartość rozwoju duchowego, moc boskich przemian i transformacji','afirmacje.pl'),
(91, 'Doceniam wartość swojego życia, doceniam wartość moich twórczych możliwości, doceniam siebie','afirmacje.pl'),
(92, 'Dokładnie wiem co robić by osiągnąć rezultaty, których chcę','afirmacje.pl'),
(93, 'Doskonale radzę sobie ze wszystkimi swoimi sprawami','afirmacje.pl'),
(94, 'Doskonale, z łatwością i na luzie zaliczam wszystkie kolokwia i egzaminy na uczelni','afirmacje.pl'),
(95, 'Doskonale, z łatwością i na luzie zaliczam wszystkie sprawdziany w szkole','afirmacje.pl'),
(96, 'Dostrzegam i doceniam moje zdolności, możliwości, atuty, mocne strony i zalety','afirmacje.pl'),
(97, 'Dostrzegam i doceniam swoją urodę, swoją mądrość, swoją zaradność, całego siebie','afirmacje.pl'),
(98, 'Dostrzegam i pozwalam sobie korzystać z boskiej mocy i twórczego potencjału we mnie','afirmacje.pl'),
(99, 'Dostrzegam i realizuję drogę sukcesu w moim życiu','afirmacje.pl'),
(100, 'Dostrzegam jak moje twórcze pomysły przyczyniają się do wzrostu bogactwa mojego i innych','afirmacje.pl'),
(101, 'Dostrzegam sens w swoim obecnym życiu i w tym, co robię','afirmacje.pl'),
(102, 'Dostrzegam swoją prawdziwą wartość, odczuwam bożą miłość do mnie','afirmacje.pl'),
(103, 'Dostrzegam w sobie boską moc i boski potencjał twórczy, pozwalam sobie w pełni korzystać z tego','afirmacje.pl'),
(104, 'Dostrzegam, akceptuję, szanuję i doceniam całą doskonałość w sobie i wokół siebie','afirmacje.pl'),
(105, 'Dostrzegam, doceniam i przejawiam moje unikalne umiejętności, zdolności i pomysły','afirmacje.pl'),
(106, 'Dostrzegam, że Bóg juz teraz prowadzi mnie w pracy mojego życia','afirmacje.pl'),
(107, 'Dostrzegam, że na świecie jest wystarczająco dużo możliwości by każdy, również ja, spełnił swoje najpiękniejsze marzenia','afirmacje.pl'),
(108, 'Doświadczam samej radości, miłości, bogactwa i spełnienia, bez względu na to co inni wokół mnie robią, mówią i myślą','afirmacje.pl'),
(109, 'Działając z lekkością i na luzie wszystkie swoje cele osiągam na czas','afirmacje.pl'),
(110, 'Działam w sposób harmonijny, uporządkowany i płynny, bo akceptuję komfort w swoim życiu','afirmacje.pl'),
(111, 'Działanie zgodne z moimi marzeniami i planami jest dla mnie bezpieczne i korzystne','afirmacje.pl'),
(112, 'Dziękuję sobie za cierpliwość i konsekwencję w dążeniu do swoich celów','afirmacje.pl'),
(113, 'Dziękuję za bogactwo, które mnie otacza','afirmacje.pl'),
(114, 'Dziękuję za doskonałe zdrowie i samopoczucie','afirmacje.pl'),
(115, 'Dziękuję za pieniądze i bogactwo, które każdego dnia otrzymuję','afirmacje.pl'),
(116, 'Dziękuję za to, że wszystkie moje marzenia spełniają się w rzeczywistości','afirmacje.pl'),
(117, 'Dziękuję za wszystkie dary, łaski i bogactwa, które obficie do mnie napływają','afirmacje.pl'),
(118, 'Emanuję życzliwością i twórczą harmonią','afirmacje.pl'),
(119, 'Gdziekolwiek podążam spotykam nieskończone dobro, nieskończoną mądrość, nieskończoną harmonię, nieskończoną miłość','afirmacje.pl'),
(120, 'Głębokie zdrowe więzi z ludźmi są dla mnie bezpieczne i naturalne','afirmacje.pl'),
(121, 'Im mocniej kocham siebie, tym więcej promieniuje miłością na innych','afirmacje.pl'),
(122, 'Im więcej daję, tym więcej posiadam i im więcej daję, tym więcej otrzymuję','afirmacje.pl'),
(123, 'Inni ludzie lubią mnie i szanują kiedy jestem sobą','afirmacje.pl'),
(124, 'Jak magnes przyciągam do siebie pieniądze, bogactwo i pomyślność','afirmacje.pl'),
(125, 'Jestem bezpieczny i niewinny ze swoim bogactwem','afirmacje.pl'),
(126, 'Jestem bezpieczny i spokojny doświadczając nowych sytuacji','afirmacje.pl'),
(127, 'Jestem bezpieczny i szanowany, gdy mówię to, co myślę','afirmacje.pl'),
(128, 'Jestem bezpieczny i w porządku kiedy pracuję w swoim własnym tempie, w swój własny sposób','afirmacje.pl'),
(129, 'Jestem bezpieczny i w porządku kiedy uprawiam seks','afirmacje.pl'),
(130, 'Jestem bezpieczny kiedy jestem szczupły','afirmacje.pl'),
(131, 'Jestem bezpieczny kiedy się zgadzam z innymi i kiedy odmawiam','afirmacje.pl'),
(132, 'Jestem bezpieczny kiedy wprowadzam w życie swoje decyzje, bez oglądania się na poglądy innych ludzi','afirmacje.pl'),
(133, 'Jestem bezpieczny przyjaźniąc się z bogatymi ludźmi i wśród nich żyjąc','afirmacje.pl'),
(134, 'Jestem bezpieczny zawsze i wszędzie','afirmacje.pl'),
(135, 'Jestem bezpieczny, akceptowany i szanowany, kiedy znajduję się w centrum zainteresowania innych ludzi','afirmacje.pl'),
(136, 'Jestem bezpieczny, niewinny i godny wobec Boga','afirmacje.pl'),
(137, 'Jestem bezpieczny, niewinny i w porządku wobec innych, kiedy jestem sobą i realizuję swoje cele','afirmacje.pl'),
(138, 'Jestem bezpieczny, niewinny i w porządku, kiedy jestem zdrowy i zadowolony z życia','afirmacje.pl'),
(139, 'Jestem bezpieczny, niewinny i zasługuję na akceptację kiedy stawiam granice, kiedy sam decyduję o sobie','afirmacje.pl'),
(140, 'Jestem całkowicie bezpieczny i niewinny w seksie','afirmacje.pl'),
(141, 'Jestem cenny i wartościowy tylko dlatego, że jestem','afirmacje.pl'),
(142, 'Jestem cenny i wartościowy, kiedy jestem sobą i realizuję swoje cele','afirmacje.pl'),
(143, 'Jestem cenny i wartościowy, kiedy jestem szczęśliwy','afirmacje.pl'),
(144, 'Jestem cenny i wartościowy, kiedy jestem zdrowy i zadowolony z życia','afirmacje.pl'),
(145, 'Jestem cenny i wartościowy, więc pozwalam sobie na bezstronność wobec siebie i innych','afirmacje.pl'),
(146, 'Jestem cenny, wartościowy i atrakcyjny bez względu na to, jak wyglądam','afirmacje.pl'),
(147, 'Jestem cenny, wartościowy i atrakcyjny, kiedy jestem trzeźwy i przytomny','afirmacje.pl'),
(148, 'Jestem cenny, wartościowy i w porządku niezależnie od opinii i oceny innych ludzi','afirmacje.pl'),
(149, 'Jestem cenny, wartościowy i w porządku, kiedy czuję się niewinny i godny','afirmacje.pl'),
(150, 'Jestem chwalony i podziwiany, bo sam doceniam siebie oraz podziwiam to co umiem i robię','afirmacje.pl'),
(151, 'Jestem cudownie uzdrowiony, Bóg mnie uzdrowił','afirmacje.pl'),
(152, 'Jestem dla siebie źródłem szczęścia, radości, miłości i obfitości, i mam nadmiar tego','afirmacje.pl'),
(153, 'Jestem godny boskiej miłości, mądrości i mocy w sobie, i akceptuję to','afirmacje.pl'),
(154, 'Jestem godny czystej miłości, szczęścia i radości w swoim życiu, akceptuję to i doceniam','afirmacje.pl'),
(155, 'Jestem godny i zasługuję na wszystko, co Bóg i wszechświat ma dla mnie najlepszego','afirmacje.pl'),
(156, 'Jestem godny pełnego doświadczania boskiej miłości, mocy i kontaktu z Bogiem','afirmacje.pl'),
(157, 'Jestem godny szczęścia, radości, miłości i odczuwania przyjemności','afirmacje.pl'),
(158, 'Jestem godny twórczych, genialnych pomysłów, które służą mnie i innym wspaniałym ludziom','afirmacje.pl'),
(159, 'Jestem godzien szczęścia, radości, miłości i mocy Boga','afirmacje.pl'),
(160, 'Jestem godzien zdrowych, głębokich związków z ludźmi i jestem z tym bezpieczny i wolny','afirmacje.pl'),
(161, 'Jestem kochany taki, jaki jestem','afirmacje.pl'),
(162, 'Jestem kochany, akceptowany i lubiany, kiedy jestem trzeźwy i przytomny','afirmacje.pl'),
(163, 'Jestem kochany, szanowany i akceptowany, kiedy czuję się niewinny i godny','afirmacje.pl'),
(164, 'Jestem kochany, szanowany i lubiany, kiedy jestem zdrowy i zadowolony z życia','afirmacje.pl'),
(165, 'Jestem kompetentnym oferentem, z łatwością uwypuklam walory mojej oferty','afirmacje.pl'),
(166, 'Jestem niewinny i bezpieczny ze swoimi poglądami i decyzjami, mam do tego boskie prawo','afirmacje.pl'),
(167, 'Jestem niewinny i w porządku kiedy postrzegam na trzeźwo i przytomnie osoby, którym wiele zawdzięczam','afirmacje.pl'),
(168, 'Jestem niewinny i w porządku ze swoimi potrzebami seksualnymi','afirmacje.pl'),
(169, 'Jestem niewinny i w porządku, gdy odmawiam i nadal jestem lubiany','afirmacje.pl'),
(170, 'Jestem niewinny i w porządku, gdy pozwalam innym popełniać błędy i tkwić w ich ograniczeniach','afirmacje.pl'),
(171, 'Jestem niewinny kiedy zarabiam na swoich twórczych pomysłach','afirmacje.pl'),
(172, 'Jestem niewinny ze swoimi wyborami bez względu na to co mówią, myślą i robią inni ludzie','afirmacje.pl'),
(173, 'Jestem niewinny ze swoją radością i entuzjazmem, a moja partnerka cieszy się razem ze mną','afirmacje.pl'),
(174, 'Jestem niewinny, więc przestaję spodziewać się kary i otwieram się na boskie błogosławieństwa','afirmacje.pl'),
(175, 'Jestem niewinny, więc zasługuję na najwyższe dobro','afirmacje.pl'),
(176, 'Jestem niezależny od cudzych decyzji, mam własną drogę i podążam nią z lekkością, mam własne cele i realizuję je z łatwością','afirmacje.pl'),
(177, 'Jestem otwarty na pracę w idealnych dla mnie warunkach, z idealnymi dla mnie ludźmi','afirmacje.pl'),
(178, 'Jestem otwarty na przyjmowanie, dlatego pieniądze i obfitość napływają do mnie z łatwością','afirmacje.pl'),
(179, 'Jestem pytany tylko wtedy, gdy potrafię odpowiedzieć na wszystkie pytania poprawnie','afirmacje.pl'),
(180, 'Jestem radosny, pełen bogactwa i obfitości','afirmacje.pl'),
(181, 'Jestem silny i zdolny, zawsze wiem co robić, by zrealizować swoje marzenia','afirmacje.pl'),
(182, 'Jestem skuteczny kiedy jestem rozluźniony','afirmacje.pl'),
(183, 'Jestem sobie życzliwy i obdarzam się miłością, dlatego podejmuję się tylko korzystnych dla mnie działań','afirmacje.pl'),
(184, 'Jestem sobą, wyrażam swoją prawdziwą naturę bez względu na innych','afirmacje.pl'),
(185, 'Jestem spokojny i zadowolony z siebie, ocena innych ludzi mi nie zagraża, bo jestem w porządku','afirmacje.pl'),
(186, 'Jestem szanowany i akceptowany, kiedy jestem sobą i realizuję swoje cele','afirmacje.pl'),
(187, 'Jestem szanowany i akceptowany, kiedy jestem szczęśliwy','afirmacje.pl'),
(188, 'Jestem szanowany, akceptowany i lubiany przez innych, kiedy jestem sobą i realizuję swoje cele','afirmacje.pl'),
(189, 'Jestem szanowany, akceptowany i lubiany również wtedy, gdy realizuję swoje cele i osiągam sukcesy','afirmacje.pl'),
(190, 'Jestem szanowany, lubiany, chciany i potrzebny, kiedy łatwo, lekko i przyjemnie się rozwijam i korzystam z owoców swojej pracy nad sobą','afirmacje.pl'),
(191, 'Jestem teraz połączony z nieograniczoną obfitością wszechświata, pozwalam sobie z niej korzystać','afirmacje.pl'),
(192, 'Jestem twórczą, nieograniczoną istotą, z Bożą pomocą potrafię stworzyć wszystko, czego chcę','afirmacje.pl'),
(193, 'Jestem uczciwy, niewinny i w porządku, kiedy moje życie i moje dobro są najważniejsze dla mnie','afirmacje.pl'),
(194, 'Jestem uczciwy, niewinny i w porządku, również gdy robię tylko to, co jest łatwe, lekkie, przyjemne i atrakcyjne dla mnie','afirmacje.pl'),
(195, 'Jestem ukochanym dzieckiem Boga, a to daje mi nieograniczone możliwości','afirmacje.pl'),
(196, 'Jestem w pełni bezpieczny, gdy ufam sobie i innym ludziom','afirmacje.pl'),
(197, 'Jestem w pełni skoncentrowany na tym, co robię','afirmacje.pl'),
(198, 'Jestem w pełni sobą i tworzę otwarte, pełne miłości relacje z innymi','afirmacje.pl'),
(199, 'Jestem w porządku','afirmacje.pl'),
(200, 'Jestem w porządku gdy żyję własnym życiem, bo wiem, że Bóg wystarczająco troszczy się o innych','afirmacje.pl'),
(201, 'Jestem w porządku i mam prawo czuć się godnie również wtedy, kiedy popełniam błędy','afirmacje.pl'),
(202, 'Jestem w porządku kiedy pozwalam ludziom aby mnie doceniali, chwalili i wspierali','afirmacje.pl'),
(203, 'Jestem w porządku kiedy spędzam wolny czas tak jak lubię i chcę','afirmacje.pl'),
(204, 'Jestem w zdrowym, przepełnionym szczęściem, miłością i wzajemnym szacunkiem związku','afirmacje.pl'),
(205, 'Jestem wartościowym człowiekiem w oczach Boga, dlatego zawsze patrzę na siebie jak na wartościowego człowieka i odnoszę się do siebie z miłością i szacunkiem','afirmacje.pl'),
(206, 'Jestem wartościowym i cennym pracownikiem','afirmacje.pl'),
(207, 'Jestem wdzięczny za miłość, którą z hojnością przejawiam każdego dnia','afirmacje.pl'),
(208, 'Jestem wolny od nawyku dostrajania się do cudzych energii, działam będąc zogniskowany na własnej czystej esencji','afirmacje.pl'),
(209, 'Jestem wspaniałym dzieckiem Bożym, wartościowym i cennym, godnym szacunku i miłości','afirmacje.pl'),
(210, 'Jestem wyjątkową, unikatową osobą, dlatego tworzę w sposób typowy tylko dla mnie, nie oglądając się na innych','afirmacje.pl'),
(211, 'Jestem wystarczająco chciany i kochany','afirmacje.pl'),
(212, 'Jestem wystarczająco chciany, kochany i potrzebny, i to, co robię jest potrzebne, cenne i wartościowe','afirmacje.pl'),
(213, 'Jestem wystarczająco dobry i atrakcyjny pod każdym względem','afirmacje.pl'),
(214, 'Jestem wystarczająco dobry taki, jaki jestem','afirmacje.pl'),
(215, 'Jestem wystarczająco dobry, aby odnosić sukcesy we wszystkim co robię','afirmacje.pl'),
(216, 'Jestem wystarczająco kreatywny, spokojny i skoncentrowany, aby osiągać najlepsze wyniki','afirmacje.pl'),
(217, 'Jestem zadowolony z powodu mojej twórczej postawy, jestem twórczym budowniczym swojego życia','afirmacje.pl'),
(218, 'Jestem zadowolony z siebie i jestem otwarty na wszelkie pozytywne zmiany w swoim życiu','afirmacje.pl'),
(219, 'Jestem zadowolony z siebie, ze swoich twórczych pomysłów i ze sposobu w jaki je przejawiam','afirmacje.pl'),
(220, 'Jestem zaspokojony i spełniony seksualnie','afirmacje.pl'),
(221, 'Jestem zawsze bezpieczny i niewinny, również gdy zarabiam tyle ile zawsze marzyłem, a nawet więcej','afirmacje.pl'),
(222, 'Jestem zdecydowany zrealizować moje najpiękniejsze marzenia, bez oglądania się na pozwolenie innych','afirmacje.pl'),
(223, 'Jestem zdrowy, zasługuję na życie i na miłość','afirmacje.pl'),
(224, 'Jestem świętą manifestacją Boga','afirmacje.pl'),
(225, 'Już nie muszę uciekać od życia, bo jestem bezpieczny tu i teraz','afirmacje.pl'),
(226, 'Już teraz jestem spokojny, bo wiem, że Bóg mnie wspiera w nauce i rozwoju','afirmacje.pl'),
(227, 'Już teraz mogę i potrafię być szczęśliwy tu i teraz','afirmacje.pl'),
(228, 'Już teraz pracuję w idealnych dla siebie warunkach, z idealnymi dla mnie ludźmi','afirmacje.pl'),
(229, 'Już teraz przejawiam w świecie to, co urzeczywistniłem, bo dostrzegam w tym sens, dobro i korzyści','afirmacje.pl'),
(230, 'Już teraz z łatwością otrzymuję to, czego pragnę','afirmacje.pl'),
(231, 'Każda sytuacja ma co najmniej jedno pozytywne, twórcze rozwiązanie, dostrzegam to i chętnie wykorzystuję w swoim życiu','afirmacje.pl'),
(232, 'Każdego dnia integruję się ze swoją własną twórczą mocą','afirmacje.pl'),
(233, 'Każdego dnia otwieram się coraz bardziej na przypływ bogactwa i obfitości','afirmacje.pl'),
(234, 'Każdego dnia staję się coraz bogatszy pod względem duchowym, umysłowym i materialnym','afirmacje.pl'),
(235, 'Kiedy tworzę, doświadczam realnego wsparcia ze strony innych','afirmacje.pl'),
(236, 'Kocham Boga i Bóg zawsze kocha mnie','afirmacje.pl'),
(237, 'Kocham i szanuję siebie w seksie','afirmacje.pl'),
(238, 'Kocham i szanuję wszystko co tworzę, a wszystko co tworzę powstaje z bożej inspiracji','afirmacje.pl'),
(239, 'Kocham moją wyobraźnię i ufam jej','afirmacje.pl'),
(240, 'Kocham pieniądze, a one kochają mnie','afirmacje.pl'),
(241, 'Kocham siebie i swoje ciało, więc otwieram się na doskonałe zdrowie','afirmacje.pl'),
(242, 'Kocham siebie, więc pozwalam sobie przebywać w czystej energetycznie przestrzeni i w przyjemnej harmonii','afirmacje.pl'),
(243, 'Kocham zarabiać pieniądze','afirmacje.pl'),
(244, 'Kocham zarabiać pieniądze, kocham swoją pracę i siebie w pracy','afirmacje.pl'),
(245, 'Kocham, lubię, szanuję, akceptuję i doceniam siebie takim, jakim jestem','afirmacje.pl'),
(246, 'Koncentruję swoją uwagę na boskiej doskonałości we mnie i w jej przejawach w moim życiu','afirmacje.pl'),
(247, 'Kontaktując się z innymi, kontaktuję się z ich boskością','afirmacje.pl'),
(248, 'Lekko i bezwysiłkowo osiągam wymarzoną, doskonałą wagę i sylwetkę','afirmacje.pl'),
(249, 'Lubię, szanuję i doceniam to, co robię','afirmacje.pl'),
(250, 'Ludzie chętnie mi płacą za moje twórcze pomysły','afirmacje.pl'),
(251, 'Ludzie mi sprzyjają, a ja sprzyjam ludziom','afirmacje.pl'),
(252, 'Ludzie podziwiają i wspierają mnie takim, jakim jestem, z moimi twórczymi pomysłami','afirmacje.pl'),
(253, 'Ludzie są zachwyceni moją twórczością, bo ja sam doceniam siebie i to jak przejawiam moje pomysły','afirmacje.pl'),
(254, 'Mam możliwości i prawo, by odnieść sukces w każdej ważnej dla mnie dziedzinie życia','afirmacje.pl'),
(255, 'Mam odwagę działać zgodnie ze swoimi marzeniami i planami','afirmacje.pl'),
(256, 'Mam odwagę, wolę i moc dokonywania wszelkich pozytywnych zmian w swoim życiu','afirmacje.pl'),
(257, 'Mam odwagę, wolę i moc, aby działać zgodnie z moimi marzeniami i celami','afirmacje.pl'),
(258, 'Mam pełne prawo do korzystania z bogactwa tego świata dla urzeczywistnienia moich twórczych pomysłów i cudownych marzeń','afirmacje.pl'),
(259, 'Mam pod dostatkiem seksu i zbliżeń miłosnych','afirmacje.pl'),
(260, 'Mam pod dostatkiem siły i konsekwencji by osiągać wszystkie swoje zamierzenia','afirmacje.pl'),
(261, 'Mam powody do zadowolenia z siebie','afirmacje.pl'),
(262, 'Mam prawo być bogaty i cieszyć się życiem','afirmacje.pl'),
(263, 'Mam prawo być sobą, jestem bezpieczny i niewinny, kiedy jestem sobą','afirmacje.pl'),
(264, 'Mam prawo być szczęśliwy bez względu na to, czego życzą mi inni','afirmacje.pl'),
(265, 'Mam prawo być szczęśliwy i jestem bezpieczny i niewinny, kiedy jestem szczęśliwy','afirmacje.pl'),
(266, 'Mam prawo być zadowolony i radosny bez względu na nastroje innych ludzi','afirmacje.pl'),
(267, 'Mam prawo dane od Boga by kochać i być kochanym','afirmacje.pl'),
(268, 'Mam prawo do codziennego wypoczynku, relaksu i rozrywki, jestem w porządku kiedy beztrosko spędzam czas','afirmacje.pl'),
(269, 'Mam prawo do oficjalnego związku partnerskiego i jestem z tym bezpieczny','afirmacje.pl'),
(270, 'Mam prawo do łatwego, lekkiego i przyjemnego życia w godności, zdrowiu i w dostatku','afirmacje.pl'),
(271, 'Mam prawo i jestem godzien tego, by żyć i cieszyć się swoim życiem','afirmacje.pl'),
(272, 'Mam prawo odnosić sukcesy w każdej dziedzinie swojego życia','afirmacje.pl'),
(273, 'Mam prawo popełniać błędy i nadal jestem bezpieczny, niewinny i w porządku','afirmacje.pl'),
(274, 'Mam prawo wybierać sobie towarzystwo, w którym się obracam, ludzi, z którymi się kontaktuję','afirmacje.pl'),
(275, 'Mam prawo żyć i wypoczywać tak jak lubię, bez oglądania się na innych','afirmacje.pl'),
(276, 'Mam silą wolę, dzięki której zdobywam najwyższe szczyty','afirmacje.pl'),
(277, 'Mam trzeźwą i przytomną świadomość, że jestem godzien korzyści materialnych i duchowych płynących z realizacji moich talentów i pasji','afirmacje.pl'),
(278, 'Mam twórczą postawę w życiu, to zapewnia mi pełnię sukcesu materialnego i duchowego','afirmacje.pl'),
(279, 'Mam twórczą postawę wobec każdej sytuacji, wobec każdego problemu i zagadnienia','afirmacje.pl'),
(280, 'Mam wolność wyboru i możliwość dokonywania wyborów najwyższej jakości','afirmacje.pl'),
(281, 'Mam wszelkie powody, by być zadowolonym z siebie i ze swojego życia','afirmacje.pl'),
(282, 'Mam wszelkie warunki do najlepszego przejawiania twórczości w swoim życiu','afirmacje.pl'),
(283, 'Mam wystarczająco dobre pomysły i jestem wystarczająco dobry by zarabiać tyle, ile chcę i potrzebuję','afirmacje.pl'),
(284, 'Mam wystarczająco dużo entuzjazmu i mocy do działania, dostrzegam sens realizacji moich twórczych pomysłów','afirmacje.pl'),
(285, 'Mam władzę nad swoim życiem, nad swoimi decyzjami, dlatego przestaję prowokować innych do tego by mnie pilnowali, kontrolowali i ustawiali','afirmacje.pl'),
(286, 'Mam zawsze dostatek swoich własnych pomysłów, bo czerpię z nieograniczonego boskiego źródła','afirmacje.pl'),
(287, 'Miejsce, w którym się znajduję jest bezpieczne i właściwe, by przejawiać siebie prawdziwego','afirmacje.pl'),
(288, 'Miłość jest dobra, bezpieczna i przyjemna','afirmacje.pl'),
(289, 'Miłość jest najpotężniejszą siłą we Wszechświecie','afirmacje.pl'),
(290, 'Miłość uzdrawia i harmonizuje moje ciało i moje myśli','afirmacje.pl'),
(291, 'Mogę czuć się niewinnie i w porządku wobec innych, kiedy łatwo, lekko i przyjemnie się rozwijam i korzystam z owoców swojej pracy nad sobą','afirmacje.pl'),
(292, 'Mogę i potrafię być szczęśliwy bez stawiania sobie warunków','afirmacje.pl'),
(293, 'Mogę już czuć się bezpiecznie i swobodnie, bo ufam, że Bóg się mną opiekuje, prowadzi i wspiera','afirmacje.pl'),
(294, 'Mogę rozwijać się poprzez doświadczanie szczęścia, radości, miłości i przyjemności','afirmacje.pl'),
(295, 'Mogę, potrafię i chcę żyć tak jak na to mam ochotę, bez oglądania sie na innych','afirmacje.pl'),
(296, 'Moja energia jest skupiona i ukierunkowana na twórcze osiąganie moich celów','afirmacje.pl'),
(297, 'Moja energia płynie swobodnie w każdym obszarze mojego życia, dlatego swobodnie przejawiam moje twórcze inspiracje','afirmacje.pl'),
(298, 'Moja praca ma sens','afirmacje.pl'),
(299, 'Moja praca przynosi mi realne dochody','afirmacje.pl'),
(300, 'Moja praca przynosi wymierne korzyści dla mnie i dla innych','afirmacje.pl'),
(301, 'Moja praca sprawia mi radość, ponieważ realizuję się w niej twórczo','afirmacje.pl'),
(302, 'Moja praca zawodowa, zajęcia i miejsce zamieszkania harmonizują ze mną, z moim związkiem partnerskim','afirmacje.pl'),
(303, 'Moja seksualność jest czysta i niewinna','afirmacje.pl'),
(304, 'Moja twórcza postawa czyni moje życie łatwym, radosnym i spełnionym','afirmacje.pl'),
(305, 'Moja twórcza postawa jest dla mnie w pełni bezpieczna','afirmacje.pl'),
(306, 'Moja twórcza postawa przyczynia się do realnej poprawy jakości mojego życia','afirmacje.pl'),
(307, 'Moja twórczość jest pełna miłości, radości i swobody','afirmacje.pl'),
(308, 'Moja wewnętrzna boskość wypełnia mnie entuzjazmem i mocą do twórczego działania','afirmacje.pl'),
(309, 'Moja świadomość i twórcze możliwości rozszerzają się każdego dnia, korzystam z tego radośnie','afirmacje.pl'),
(310, 'Moje bogactwo materialne wspiera mnie w realizacji celu mojego życia','afirmacje.pl'),
(311, 'Moje ciało i mój umysł są wyrazem doskonałego zdrowia','afirmacje.pl'),
(312, 'Moje ciało jest darem Boga, dlatego jest czyste i niewinne','afirmacje.pl'),
(313, 'Moje ciało jest doskonale zdrowe i promieniuje światłością mojej duszy','afirmacje.pl'),
(314, 'Moje ciało jest właściwe, a ja jestem zadowolony z jego wyglądu','afirmacje.pl'),
(315, 'Moje ciało służy doświadczaniu miłości, przyjemności i wygody w pracy, związkach i w seksie','afirmacje.pl'),
(316, 'Moje ciało z każdym dniem jest coraz zdrowsze','afirmacje.pl'),
(317, 'Moje czyste, wysokie wibracje mają o wiele większą siłę sprawczą w moim życiu od wszelkich lęków i nieczystości','afirmacje.pl'),
(318, 'Moje marzenia są godne realizacji, zawsze mam wartościowe pomysły, które realizuję ze spontaniczną łatwością','afirmacje.pl'),
(319, 'Moje miejsce już na zawsze jest wśród twórczych ludzi sukcesu','afirmacje.pl'),
(320, 'Moje myśli są pełne miłości, radości i szczęścia','afirmacje.pl'),
(321, 'Moje myśli tworzą moją rzeczywistość, dlatego skupiam się na tym, czego chcę','afirmacje.pl'),
(322, 'Moje myśli, słowa i działania są wypełnione boską mądrością','afirmacje.pl'),
(323, 'Moje myśli, słowa i działania są wypełnione czysta boskością','afirmacje.pl'),
(324, 'Moje najpiękniejsze marzenia spełniają się w rzeczywistości','afirmacje.pl'),
(325, 'Moje pomysły wzrastają i owocują w bożej w łasce','afirmacje.pl'),
(326, 'Moje relacje z innymi przepełnione są harmonią i porozumieniem','afirmacje.pl'),
(327, 'Moje talenty są Bożymi darami dla mnie i dla innych','afirmacje.pl'),
(328, 'Moje uzdrowienie ma sens, pozwalam sobie na skuteczne, pozytywne zmiany','afirmacje.pl'),
(329, 'Moje wewnętrzne, boskie prowadzenie kieruje mnie do najszybszych i najprostszych rozwiązań','afirmacje.pl'),
(330, 'Moje wnętrze jest wypełnione twórczymi pomysłami na życie, które realizuję z miłości do siebie','afirmacje.pl'),
(331, 'Moje wszystkie marzenia są napełnione energią sukcesu','afirmacje.pl'),
(332, 'Moje życie i to czego pragnę jest ważne, więc traktuję to z szacunkiem','afirmacje.pl'),
(333, 'Moje życie i to, co robię ma sens, jest ciekawe, przyjemne i oświecające','afirmacje.pl'),
(334, 'Moje życie ma sens','afirmacje.pl'),
(335, 'Moje życie ma sens i jest ciekawe, gdy realizuję swoje cele','afirmacje.pl'),
(336, 'Moje życie ma sens, moja praca ma sens i wszystko to, co robię ma sens','afirmacje.pl'),
(337, 'Moje życie ma sens, więc akceptuję i doceniam to, czego doświadczam','afirmacje.pl'),
(338, 'Moje życie przepełnione jest Miłością','afirmacje.pl'),
(339, 'Moje życie wypełnione jest miłością i ważnymi dla mnie działaniami','afirmacje.pl'),
(340, 'Mój seks jest bezpieczny, czysty i niewinny','afirmacje.pl'),
(341, 'Mój umysł i moja pamięć są wystarczająco sprawne','afirmacje.pl'),
(342, 'Mój umysł i serce kieruję ku wewnętrznej obecności Boga','afirmacje.pl'),
(343, 'Mój umysł jest czysty, twórczy i przytomny, emanuje światłością i mądrością','afirmacje.pl'),
(344, 'Mój umysł jest darem Boga, w związku z tym jest doskonały i genialny','afirmacje.pl'),
(345, 'Mój umysł należy do mnie i jest wolny od spełniania cudzych zachcianek','afirmacje.pl'),
(346, 'Mówię w sposób jasny i zrozumiały o sobie i swoich pragnieniach','afirmacje.pl'),
(347, 'Nie muszę być idealny; wystarczy, że jestem sobą','afirmacje.pl'),
(348, 'Oczekuję tylko najlepszego rozwiązania i to się dzieje','afirmacje.pl'),
(349, 'Odczuwając miłość jestem czysty i niewinny','afirmacje.pl'),
(350, 'Odczuwam Boże wsparcie kiedy zarabiam na luzie, w łatwy i szybki sposób','afirmacje.pl'),
(351, 'Odpuszczam i przebaczam swoim rodzicom wyrządzone mi krzywdy','afirmacje.pl'),
(352, 'Odpuszczam i przebaczam wszystkim, którzy mnie skrzywdzili','afirmacje.pl'),
(353, 'Osiągam wszystko o czym marzę','afirmacje.pl'),
(354, 'Osiąganie przeze mnie najlepszych wyników bez żadnego wysiłku jest całkowicie sprawiedliwe, bezpieczne i w porządku','afirmacje.pl'),
(355, 'Osiąganie sukcesów i przyjemności jest dla mnie w pełni bezpieczne i oświecające, więc jestem z tym niewinny i w porządku','afirmacje.pl'),
(356, 'Otaczam się ludźmi, którzy tak jak ja, potrafią ze spokojem osiągać najlepsze wyniki bez żadnego wysiłku','afirmacje.pl'),
(357, 'Otaczam się przyjaznymi, pomocnymi i mądrymi ludźmi','afirmacje.pl'),
(358, 'Otaczam się takimi nauczycielami, którzy wiedzą, że zasługuję na najlepsze wyniki','afirmacje.pl'),
(359, 'Otwieram się i dostrajam się tylko do wysokich, czystych wibracji, energii','afirmacje.pl'),
(360, 'Otwieram się i jestem gotowy na polepszenie swojej sytuacji, dostrzegam nowe, nawet zaskakujące możliwości poprawy i ułatwień','afirmacje.pl'),
(361, 'Otwieram się na bogactwo materialne i duchowe','afirmacje.pl'),
(362, 'Otwieram się na całe dobro i szczęście; zasługuję na nie','afirmacje.pl'),
(363, 'Otwieram się na cudowne, pełne uzdrowienie swojego ciała','afirmacje.pl'),
(364, 'Otwieram się na cudowny, rozkoszny seks','afirmacje.pl'),
(365, 'Otwieram się na doświadczanie samej radości i przyjemności w swoim życiu','afirmacje.pl'),
(366, 'Otwieram się na moje najwyższe dobro w każdym obszarze mojego życia','afirmacje.pl'),
(367, 'Otwieram się na moje najwyższe dobro, przejawiam już teraz w moich myślach, słowach i czynach','afirmacje.pl'),
(368, 'Otwieram się na relacje w których jestem doceniany, bo sam doceniam siebie','afirmacje.pl'),
(369, 'Otwieram się na twórcze wyrażenie mojej indywidualności w życiu, w codziennym działaniu, w osiąganiu celów','afirmacje.pl'),
(370, 'Otwieram się na wysokie zarobki','afirmacje.pl'),
(371, 'Oświecam się na trzeźwo i przytomnie w pracy, twórczości, związku miłości i w seksie','afirmacje.pl'),
(372, 'Pieniądze płyną do mnie nieustannie z wielu źródeł','afirmacje.pl'),
(373, 'Pieniądze są dla mnie darem Bożym i zawsze mam ich wystarczającą ilość','afirmacje.pl'),
(374, 'Pisanie afirmacji jest dla mnie miłe i przyjemne','afirmacje.pl'),
(375, 'Planuję i realizuję swoje pomysły z łatwością, a życie mnie w tym wspiera radosnymi niespodziankami','afirmacje.pl'),
(376, 'Podchodzę na luzie i spokojnie do seksu, dlatego potrafię się nim cieszyć do woli','afirmacje.pl'),
(377, 'Poddając się boskiemu prowadzeniu, radośnie i przytomnie wyrażam swój twórczy potencjał','afirmacje.pl'),
(378, 'Poddaję się twórczemu procesowi życia, bo wiem, że życie jest dla mnie, życie udziela mi wsparcia','afirmacje.pl'),
(379, 'Podlegam wyłącznie boskiemu prowadzeniu i boskiej opiece','afirmacje.pl'),
(380, 'Podziwiam siebie, bo doceniam wszystkie swoje twórcze działania, na których korzystam ja i inni wspaniali ludzie','afirmacje.pl'),
(381, 'Podążam za czystą radością, to zapewnia mi sukces','afirmacje.pl'),
(382, 'Podążam za swoimi wewnętrznymi pragnieniami i odczuciami, słucham i działam w oparciu o boskie prowadzenie','afirmacje.pl'),
(383, 'Ponieważ jestem twórczy, to zawsze i wszędzie jestem wolny, niezależny, swobodny i zaradny','afirmacje.pl'),
(384, 'Ponieważ moje marzenia są realne do osiągnięcia, to jestem gotowy je spełnić','afirmacje.pl'),
(385, 'Ponieważ sam jestem życzliwie nastawiony do siebie i innych, to ludzie są dla mnie przyjaźni','afirmacje.pl'),
(386, 'Postrzegam siebie i swoje miejsce w życiu jako osoby wolnej, czystej, niezależnej od cudzych wyobrażeń i będącej w porządku ze swoimi wyborami','afirmacje.pl'),
(387, 'Potrafię być trzeźwy i niezależny wobec presji, oczekiwań i manipulacji innych ludzi','afirmacje.pl'),
(388, 'Potrafię być zadowolony z siebie','afirmacje.pl'),
(389, 'Potrafię być zadowolony z siebie, ze swojego wyglądu, ze swojego życia i mam do tego coraz więcej powodów','afirmacje.pl'),
(390, 'Potrafię cierpliwie, zdecydowanie i ufnie, realizować swoje długoterminowe cele','afirmacje.pl'),
(391, 'Potrafię czuć prawdziwy sens swojego życia','afirmacje.pl'),
(392, 'Potrafię korzystać z wsparcia osób sprzyjających mojej twórczej postawie','afirmacje.pl'),
(393, 'Potrafię odczuwać szczęście, radość i miłość Boga','afirmacje.pl'),
(394, 'Potrafię się cieszyć z obecnego stanu rzeczy i doceniam to, co już osiągnąłem','afirmacje.pl'),
(395, 'Potrafię widzieć jasno i podejmować efektywne decyzje we wszystkich dziedzinach mojego życia','afirmacje.pl'),
(396, 'Potrafię wykorzystywać wszystkie nadarzające się okazje na dobry zarobek','afirmacje.pl'),
(397, 'Potrafię z czystymi intencjami przyjmować życzliwą pomoc od innych ludzi','afirmacje.pl'),
(398, 'Potrafię zachować dobry nastrój, a nawet czuć się komfortowo również wtedy, gdy inni są niezadowoleni z moich wyborów','afirmacje.pl'),
(399, 'Potrafię zrobić wszystko, czego naprawdę pragnę','afirmacje.pl'),
(400, 'Powierzam Bogu moje serce, moje ciało i mój umysł','afirmacje.pl'),
(401, 'Powierzam Bogu oczyszczenie i uzdrowienie mojego życia seksualnego','afirmacje.pl'),
(402, 'Powierzam się boskiemu prowadzeniu w seksie','afirmacje.pl'),
(403, 'Poznając nowych ludzi czuję się pewnie i bezpiecznie','afirmacje.pl'),
(404, 'Poznaję istotę mojego największego talentu, pozwalam sobie, na przejawienie go w życiu','afirmacje.pl'),
(405, 'Pozwalam sobie myśleć, marzyć i działać w nieograniczony sposób','afirmacje.pl'),
(406, 'Pozwalam sobie na doskonałe zdrowie','afirmacje.pl'),
(407, 'Pozwalam sobie na pełne zaspokojenie seksualne','afirmacje.pl'),
(408, 'Pozwalam sobie na pełną akceptację i docenienie siebie i swojego ciała niezależnie od wyobrażeń, oczekiwań i opinii innych ludzi','afirmacje.pl'),
(409, 'Pozwalam sobie na seks najwyższej jakości','afirmacje.pl'),
(410, 'Pozwalam sobie na wolność i spontaniczność w seksie','afirmacje.pl'),
(411, 'Pozwalam sobie osiągać najlepsze wyniki łatwo i bez wysiłku','afirmacje.pl'),
(412, 'Pozwalam sobie zachować przytomność i trzeźwość umysłu również wówczas, gdy ktoś ocenia mnie i owoce moich twórczych pomysłów','afirmacje.pl'),
(413, 'Pozwalam światu cieszyć się moimi talentami','afirmacje.pl'),
(414, 'Pozwalam światu obficie wynagradzać mnie za możliwość korzystania z moich talentów','afirmacje.pl'),
(415, 'Praca istnieje dla mojej radości, wygody i przyjemności','afirmacje.pl'),
(416, 'Pracuję z chęcią i efektywnie, to daje mi zadowolenie i spełnienie','afirmacje.pl'),
(417, 'Promieniuję poczuciem godności, spokojem, miłością, pomyślnością i szczęściem','afirmacje.pl'),
(418, 'Promieniuję spokojem i pewnością sukcesu bez względu na to, co dzieje się wokół mnie','afirmacje.pl'),
(419, 'Prowadzenie twórczego, dostatniego i komfortowego życia pełnego sukcesów jest w pełni zgodne z moją naturą','afirmacje.pl'),
(420, 'Prowadzę coraz bardziej twórcze, radosne, harmonijne i spełnione życie','afirmacje.pl'),
(421, 'Prowadzę radosne, harmonijne i spełnione życie','afirmacje.pl'),
(422, 'Przebaczam całkowicie wszystkim, którzy wmawiali mi bzdury na mój temat','afirmacje.pl'),
(423, 'Przebaczam całkowicie wszystkim, którzy wmawiali mi bzdury na temat Boga i rozwoju duchowego','afirmacje.pl'),
(424, 'Przebaczam innym, że mnie obwiniali','afirmacje.pl'),
(425, 'Przebaczam innym, że ulegali moim prowokacjom do karania mnie i obwiniania','afirmacje.pl'),
(426, 'Przebaczam moim rodzicom, że krzyczeli na mnie i kazali mi siedzieć cicho','afirmacje.pl'),
(427, 'Przebaczam moim rodzicom, że mnie ogłupiali, obwiniali karali i ograniczali','afirmacje.pl'),
(428, 'Przebaczam sobie oddzielenie się od Boga','afirmacje.pl'),
(429, 'Przebaczam sobie poczucie winy i niegodności','afirmacje.pl'),
(430, 'Przebaczam sobie wszelkie intencje i mechanizmy obwiniania i karania siebie za doznane krzywdy','afirmacje.pl'),
(431, 'Przebaczam sobie wszystkie rozczarowania','afirmacje.pl'),
(432, 'Przebaczam sobie zaślepienie na głupotę i nauki mistrzów i guru','afirmacje.pl'),
(433, 'Przebaczam sobie, ze odwróciłem się od Boga, zwalniam się z pokuty za to','afirmacje.pl'),
(434, 'Przebaczam sobie, że gardziłem ludźmi, bogactwem i seksem','afirmacje.pl'),
(435, 'Przebaczam sobie, że myślałem, że Bóg zabrania mi seksu i związków seksualnych','afirmacje.pl'),
(436, 'Przebaczam sobie, że mściłem się na rodzicach za doznane od nich krzywdy','afirmacje.pl'),
(437, 'Przebaczam sobie, że nie doceniałem siebie i tego, co robiłem','afirmacje.pl'),
(438, 'Przebaczam sobie, że nie szanowałem siebie i ograniczałem swoje potrzeby i pragnienia','afirmacje.pl'),
(439, 'Przebaczam sobie, że niewłaściwie korzystałem ze swojego ciała, że nadużywałem je i niszczyłem','afirmacje.pl'),
(440, 'Przebaczam sobie, że obrzydzałem sobie seks i związki seksualne','afirmacje.pl'),
(441, 'Przebaczam sobie, że obrzydzałem sobie życie w ciele','afirmacje.pl'),
(442, 'Przebaczam sobie, że obwiniałem Boga za moje błędy, porażki i upadki','afirmacje.pl'),
(443, 'Przebaczam sobie, że obwiniałem siebie','afirmacje.pl'),
(444, 'Przebaczam sobie, że obwiniałem się za błędy swoich rodziców i że karałem siebie za to','afirmacje.pl'),
(445, 'Przebaczam sobie, że obwiniałem się za swoje błędy, porażki i upadki, i że karałem siebie za to','afirmacje.pl'),
(446, 'Przebaczam sobie, że oczekiwałem od innych kary','afirmacje.pl'),
(447, 'Przebaczam sobie, że ograniczałem się finansowo','afirmacje.pl'),
(448, 'Przebaczam sobie, że pozwalałem się wykorzystywać i krzywdzić','afirmacje.pl'),
(449, 'Przebaczam sobie, że prowokowałem moich rodziców, aby mnie karali i ograniczali','afirmacje.pl'),
(450, 'Przebaczam sobie, że rezygnowałem z siebie, ze swojego bogactwa duchowego i materialnego oraz z radości ze swojego życia w tym świecie','afirmacje.pl'),
(451, 'Przebaczam sobie, że siebie ogłupiałem, obwiniałem, karałem i ograniczałem','afirmacje.pl'),
(452, 'Przebaczam sobie, że uwierzyłem w urojenia i ograniczenia innych ludzi','afirmacje.pl'),
(453, 'Przebaczam sobie, że zwracałem na siebie uwagę swoimi dolegliwościami','afirmacje.pl'),
(454, 'Przebaczam wszystkim, którzy mnie ogłupili, zmanipulowali i wykorzystali','afirmacje.pl'),
(455, 'Przebaczam wszystkim, którzy mnie okłamywali, ogłupiali i ograniczali','afirmacje.pl'),
(456, 'Przebaczam wszystkim, którzy obrzydzali mi seks i związki seksualne','afirmacje.pl'),
(457, 'Przebaczam wszystkim, którzy obrzydzali mi życie w ciele','afirmacje.pl'),
(458, 'Przebaczam wszystkim, którzy przyczynili się do tego, że rezygnowałem z siebie i swojego bogactwa duchowego i materialnego','afirmacje.pl'),
(459, 'Przedstawiając swoją ofertę czuję się pewnie i swobodnie, dlatego działam skutecznie','afirmacje.pl'),
(460, 'Przejawiam siebie, płynąc z radosnym nurtem życia','afirmacje.pl'),
(461, 'Przejawiam się twórczo i na luzie, a Bóg to pochwala','afirmacje.pl'),
(462, 'Przejawianie pełni swojej boskości w ciele jest dla mnie możliwe, bezpieczne i naturalne','afirmacje.pl'),
(463, 'Przejawianie siebie jest dla mnie łatwe, bezpieczne i korzystne','afirmacje.pl'),
(464, 'Przekonuję się, że działam skutecznie kiedy jestem na luzie','afirmacje.pl'),
(465, 'Przekonuję się, że moc Boga jest realna tu, w tym świecie','afirmacje.pl'),
(466, 'Przekonuję się, że świat jest dla mnie bezpiecznym miejscem','afirmacje.pl'),
(467, 'Przyciągam do siebie tylko zdrowe relacje, ludzie zawsze dobrze mnie traktują','afirmacje.pl'),
(468, 'Przyciągam do swojego życia coraz więcej harmonijnych osób, z którymi spontanicznie doświadczam radości, miłości, bogactwa i spełnienia','afirmacje.pl'),
(469, 'Przyciągam ludzi, którzy chętnie mi płacą za moje pomysły i ich owoce','afirmacje.pl'),
(470, 'Przyciągam sytuacje i ludzi którzy prowadzą mnie do pełnej realizacji pracy mojego życia','afirmacje.pl'),
(471, 'Realizacja moich twórczych pomysłów, przedsięwzięć, daje mi zadowolenie i dobre dochody','afirmacje.pl'),
(472, 'Rezygnuje z telepatycznego ściągania informacji o sobie i świecie od innych ludzi','afirmacje.pl'),
(473, 'Rezygnuje z wyobrażeń na temat mojej Prawdziwej Natury, pozwalam sobie poznać jej istotę','afirmacje.pl'),
(474, 'Rezygnuję z bycia ofiarą, jestem i zawsze byłem całkowicie niewinny i w porządku','afirmacje.pl'),
(475, 'Rezygnuję z dostrajania się do cudzych presji, Bóg i tylko Bóg ma niepodzielną władzę nade mną','afirmacje.pl'),
(476, 'Rezygnuję z kombinacji myślowych na rzecz jasności, mądrości i inspiracji Boga, które zawsze łatwo i lekko przejawiam','afirmacje.pl'),
(477, 'Rezygnuję z krytykowania i poniżania siebie','afirmacje.pl'),
(478, 'Rezygnuję z obwiniania się i użalania się nad sobą, wiem, że potrafię tworzyć rzeczywistość jaką chcę i tak czynię z Bożym wsparciem','afirmacje.pl'),
(479, 'Rezygnuję z odpokutowywania biedą','afirmacje.pl'),
(480, 'Rezygnuję z podatności na presje i manipulacje innych ludzi, zwłaszcza moich bliskich','afirmacje.pl'),
(481, 'Rezygnuję z podłączania się pod cudze stany emocjonalne i przejmowania ich jako własne','afirmacje.pl'),
(482, 'Rezygnuję z pogoni za szczęściem, a pozwalam sobie doświadczać szczęścia tu i teraz','afirmacje.pl'),
(483, 'Rezygnuję z porównywania się z innymi, otwieram się na pełnię własnej doskonałości','afirmacje.pl'),
(484, 'Rezygnuję z sabotowania sobie dużych i łatwych sukcesów finansowych; w miejsce tego otwieram się na spektakularne zarobki','afirmacje.pl'),
(485, 'Rezygnuję z walki, otwieram drogę dla miłości w moim sercu i to jest dla mnie bezpieczne i korzystne','afirmacje.pl'),
(486, 'Rezygnuję z zachłanności na bycie podziwianym','afirmacje.pl'),
(487, 'Rezygnuję z zazdrości, porównywania się i rywalizowania z innymi','afirmacje.pl'),
(488, 'Rezygnuję ze spełniania cudzych oczekiwań, jestem bezpieczny, kiedy realizuję własne marzenia','afirmacje.pl'),
(489, 'Robię to co jest sensowne, ciekawe i przyjemne','afirmacje.pl'),
(490, 'Rozwijam się duchowo, doświadczając samych przyjemności i zadowolenia w swoim życiu','afirmacje.pl'),
(491, 'Sam wiem co dobre i właściwe, więc rezygnuję z oglądania się na innych','afirmacje.pl'),
(492, 'Sam wiem, czego chcę i z bożą pomocą osiągam to bez oglądania się na innych','afirmacje.pl'),
(493, 'Staję się w pełni zdrowy - harmonijnie gospodaruję swoją energią','afirmacje.pl'),
(494, 'Sukces jest moim Boskim przeznaczeniem','afirmacje.pl'),
(495, 'Szanuję moją żywotność we wszystkim, co robię przejawiam twórczość w działaniu','afirmacje.pl'),
(496, 'Szanuję siebie we wszystkim, co robię','afirmacje.pl'),
(497, 'Słucham i zwracam uwagę na podszepty mojej duszy','afirmacje.pl'),
(498, 'Teraz dostrzegam, że opłaca mi się być twórczym, dlatego otwieram się na przejawianie mojego twórczego potencjału','afirmacje.pl'),
(499, 'Teraz mam nowe, twórcze rozwiązania dla realizacji moich marzeń i planów','afirmacje.pl'),
(500, 'Teraz wszystko w moim życiu zależy wyłącznie ode mnie i jest to bezpieczne dla mnie','afirmacje.pl'),
(501, 'To bezpieczne i korzystne zaufać i powierzyć Bogu siebie, swoją pracę, związek miłości i seks','afirmacje.pl'),
(502, 'To bezpieczne i w porządku, gdy uczę się szybko, łatwo i przyjemnie','afirmacje.pl'),
(503, 'To bezpieczne kiedy na trzeźwo i przytomnie jestem świadomy siebie, swoich odczuć i reakcji','afirmacje.pl'),
(504, 'To bezpieczne, naturalne i boskie dla mnie mieć własne zdanie i gust','afirmacje.pl'),
(505, 'To co robię jest potrzebne światu, świat korzysta na mojej twórczości','afirmacje.pl'),
(506, 'To uczciwe i w porządku kiedy bez wysiłku zdaję wszystkie egzaminy, bez względu na to co inni robią, mówią i myślą','afirmacje.pl'),
(507, 'To w porządku gdy czuję i przejawiam radość, nawet gdy inni cierpią','afirmacje.pl'),
(508, 'To w porządku i bezpieczne, kiedy pozwalam innym aby dostrzegli i docenili mój prawdziwy, boski potencjał','afirmacje.pl'),
(509, 'To w porządku kiedy łatwo i szybko się bogacę','afirmacje.pl'),
(510, 'To w porządku, gdy zarabiam wiele, małym kosztem','afirmacje.pl'),
(511, 'To w porządku, że jestem niezależny, wolny od przymusu ulegania innym','afirmacje.pl'),
(512, 'To w porządku, że jestem; mam pełne prawo do życia','afirmacje.pl'),
(513, 'To, co robię dla siebie ma sens i przynosi widoczne efekty we właściwym czasie','afirmacje.pl'),
(514, 'To, czym się teraz zajmuję, jest dla mnie najważniejsze na świecie','afirmacje.pl'),
(515, 'Tworzę pod Bożą ochroną, a konsekwencje mojej twórczości służą mojemu najwyższemu dobru','afirmacje.pl'),
(516, 'Tworzę to, czego chcę, skupiając się na esencji mojego pragnienia','afirmacje.pl'),
(517, 'Tworzę, bo jestem','afirmacje.pl'),
(518, 'Twórcza radość i entuzjastyczna postawa zawsze towarzyszy mi w drodze osiągania celów','afirmacje.pl'),
(519, 'Twórcze sukcesy innych wspierają moje sukcesy','afirmacje.pl'),
(520, 'Twórcze zmiany, które następują w moim życiu, są dla mnie bezpiecznie, ponieważ sam Bóg mnie prowadzi, ochrania i wspiera','afirmacje.pl'),
(521, 'Uczę się szybko, łatwo i skutecznie','afirmacje.pl'),
(522, 'Ufam bożemu prowadzeniu, dlatego rezygnuję z szukania potwierdzenia swoich wyborów w umysłach innych ludzi','afirmacje.pl'),
(523, 'Ufam mojej intuicji, to mi się opłaca','afirmacje.pl'),
(524, 'Ufam mojej intuicji, wszystkie potrzebne odpowiedzi są wewnątrz mnie','afirmacje.pl'),
(525, 'Ufam procesowi życia i jestem z tym bezpieczny','afirmacje.pl'),
(526, 'Ufam sile Miłości, która mnie prowadzi','afirmacje.pl'),
(527, 'Ufam sobie i słucham głosu boskiej mądrości we mnie i działam zgodnie z nim','afirmacje.pl'),
(528, 'Ufam, że moja przyszłość jest bezpieczna i pełna cudownych boskich niespodzianek','afirmacje.pl'),
(529, 'Ujawniam się, rezygnuję z ukrywania moich talentów i mocy, pozwalam, aby w pełni rozkwitły wszystkie moje twórcze zdolności','afirmacje.pl'),
(530, 'Utrzymuję stałą wizję, że wszystko, co przychodzi do mnie w każdej sytuacji jest najwyższej jakości i tak się dzieje','afirmacje.pl'),
(531, 'Uwalniam się całkowicie i do końca od całego pomieszania na temat sensu i skuteczności pracy nad sobą','afirmacje.pl'),
(532, 'Uwalniam się od nawyku i przymusu brania odpowiedzialności za nastroje innych ludzi','afirmacje.pl'),
(533, 'Uwalniam się od ograniczających mnie starych schematów myślowych i lęków','afirmacje.pl'),
(534, 'Uwalniam się od poczucia winy','afirmacje.pl'),
(535, 'Uwalniam się od pretensji i żalów wobec ludzi, od których dotychczas czułem się zależny','afirmacje.pl'),
(536, 'Uwalniam się od wszelkich blokad i ograniczeń, które nie pozwalały mi w pełni wyrażać i realizować siebie','afirmacje.pl'),
(537, 'Uwalniam się od wszelkich intencji prowokowania ludzi, aby wywierali na mnie presje','afirmacje.pl'),
(538, 'Uwalniam się od wszelkich intencji, przymusów i mechanizmów karania siebie i ograniczania siebie','afirmacje.pl'),
(539, 'Uwalniam się od wszelkich urojeń na temat własnych ograniczeń, w ich miejsce dostrzegam swój boski potencjał, uczę się korzystać z niego','afirmacje.pl'),
(540, 'Uwalniam się od zaślepienia, że inni są lepsi ode mnie, a ja nie jestem godzien spełnienia','afirmacje.pl'),
(541, 'Uwielbiam pisać afirmacje','afirmacje.pl'),
(542, 'Ułatwiam sobie życie pod każdym względem, niezależnie od innych','afirmacje.pl'),
(543, 'Uświadamiam sobie głęboki, duchowy sens mojego życia','afirmacje.pl'),
(544, 'Uświadamiam sobie naturę pracy mojego życia, wiem coraz precyzyjniej jak przejawiać ją w moim życiu','afirmacje.pl'),
(545, 'Uświadamiam sobie, czym jest mój twórczy potencjał i jakie daje mi możliwości','afirmacje.pl'),
(546, 'Uświadamiam sobie, na czym polega potencjał drzemiący w każdej boskiej istocie, również we mnie','afirmacje.pl'),
(547, 'Uświadamiam sobie, że mój twórczy potencjał jest nieskończony, ponieważ jego źródłem jest sam Bóg','afirmacje.pl'),
(548, 'W dzień i w nocy wszystko mi sprzyja','afirmacje.pl'),
(549, 'W każdej chwili jestem całkowicie spokojny i skoncentrowany na tym, co jest dla mnie ważne','afirmacje.pl'),
(550, 'W każdej chwili potrafię poprawnie rozwiązać zadanie i odpowiedzieć na wszystkie pytania','afirmacje.pl'),
(551, 'W moim otoczeniu zawsze znajdują się ludzie, którzy wspierają urzeczywistnianie moich twórczych pomysłów','afirmacje.pl'),
(552, 'W moim związku partnerskim realizuje się to wszystko, co Bóg ma dla nas najlepszego','afirmacje.pl'),
(553, 'W relacjach z innymi jestem sobą, to jest w porządku, gdy zawsze jestem sobą','afirmacje.pl'),
(554, 'Wdzięczność otwiera mnie na jeszcze więcej','afirmacje.pl'),
(555, 'We mnie jest doskonały Bóg, a ja pozwalam sobie być czystym kanałem dla Niego','afirmacje.pl'),
(556, 'Widzę, że mój indywidualizm jest moim atutem, zawsze trafiam na okoliczności, w których umiem twórczo go przejawić','afirmacje.pl'),
(557, 'Wiem co zamierzam stworzyć w moim życiu, ustalam swoje cele i jestem gotowy na ich spełnienie','afirmacje.pl'),
(558, 'Wiem, że energia sukcesu ma większą moc sprawczą niż wszelkie moje obawy i lęki','afirmacje.pl'),
(559, 'Wiem, że wszechświat działa ze mną i dla mnie','afirmacje.pl'),
(560, 'Wierzę w siebie bo wiem, że z Bożą pomocą potrafię stworzyć wszystko, czego chcę','afirmacje.pl'),
(561, 'Wierzę w siebie i w realizację swoich marzeń','afirmacje.pl'),
(562, 'Wnoszę do świata własną radosną twórczość, dlatego mam sprzyjające okoliczności przejawienia się','afirmacje.pl'),
(563, 'Wszechświat działa w sposób doskonały, zawsze służy mojemu najwyższemu dobru','afirmacje.pl'),
(564, 'Wszechświat mi sprzyja','afirmacje.pl'),
(565, 'Wszechświat mi sprzyja gdy wyrażam swoją prawdziwą naturę, Bóg prowadzi mnie do osiągnięcia mojego celu życia','afirmacje.pl'),
(566, 'Wszelkie prowadzenie, którego potrzebuję, jest we mnie','afirmacje.pl'),
(567, 'Wszystkie moje intencje dotyczące przejawiania moich unikatowych talentów uzdrawiają się teraz całkowicie i do końca','afirmacje.pl'),
(568, 'Wszystkie moje zamierzenia i marzenia osiągam z sukcesem','afirmacje.pl'),
(569, 'Wszystko co robię jest cenne i wartościowe','afirmacje.pl'),
(570, 'Wszystko co robię jest dobre, pełne miłości, radości i bogactwa','afirmacje.pl'),
(571, 'Wszystko czego potrzebuję jest wewnątrz mnie i czeka by to przejawić','afirmacje.pl'),
(572, 'Wszystko czego potrzebuję mam zawsze we właściwym czasie','afirmacje.pl'),
(573, 'Wszystko jest dla mnie możliwe dzięki boskiej opiece, dzięki odwoływaniu się do intuicji','afirmacje.pl'),
(574, 'Wsłuchuję się w prowadzenie mojej duszy, dlatego znam istotę mojego szczęścia','afirmacje.pl'),
(575, 'Wybaczam innym, że hamowali moje twórcze przejawianie się','afirmacje.pl'),
(576, 'Wybaczam sobie brak wiary w moją skuteczność, w moją MOC','afirmacje.pl'),
(577, 'Wybaczam sobie zaślepienie, że w moich oczach Bóg mnie porzucił','afirmacje.pl'),
(578, 'Wybaczam sobie, że czułem się słabszy i gorszy od innych','afirmacje.pl'),
(579, 'Wybaczam sobie, że czułem się winny z powodu moich potrzeb seksualnych','afirmacje.pl'),
(580, 'Wybaczam sobie, że krytykowałem siebie i prowokowałem do tego innych','afirmacje.pl'),
(581, 'Wybaczam sobie, że prowokowałem innych aby mnie nie szanowali','afirmacje.pl'),
(582, 'Wybaczam sobie, że uwierzyłem w to, że aby osiągać swoje cele trzeba kombinować, udawać i wyrzekać się siebie','afirmacje.pl'),
(583, 'Wybaczam sobie, że w przeszłości nie pozwalałem sobie na pełne zaspokojenie i spełnienie w seksie','afirmacje.pl'),
(584, 'Wybaczam sobie, że w przeszłości realizowałem swoje pomysły w sposób niekorzystny dla mnie','afirmacje.pl'),
(585, 'Wybaczam sobie, że wierzyłem w swoją niemoc i oddałem innym ludziom władzę nad swoim życiem','afirmacje.pl'),
(586, 'Wybaczam sobie, że wyrzekłem się przejawiania swoich talentów i wstydziłem się swojej niepowtarzalności','afirmacje.pl'),
(587, 'Wybaczam sobie, że zrezygnowałem z własnych marzeń','afirmacje.pl'),
(588, 'Wybieram pozytywne nastawienie w każdej sytuacji w moim życiu','afirmacje.pl'),
(589, 'Wybieram przyjemną, szybką, łatwą i skuteczną naukę','afirmacje.pl'),
(590, 'Wybieram radosne, szczęśliwe, miłe, bogate i spełnione życie na trzeźwo i przytomnie','afirmacje.pl'),
(591, 'Wybieram rozwój duchowy na trzeźwo i przytomnie','afirmacje.pl'),
(592, 'Wybieram rozwój poprzez radość i twórcze spełnienie','afirmacje.pl'),
(593, 'Wybieram satysfakcjonującą mnie pracę','afirmacje.pl'),
(594, 'Wybieram swój rozwój poprzez doświadczanie szczęścia, radości, miłości i przyjemności','afirmacje.pl'),
(595, 'Wybieram trzeźwe i przytomne postrzeganie Boga i mojej relacji z Bogiem','afirmacje.pl'),
(596, 'Wybieram trzeźwe i przytomne postrzeganie bogactwa duchowego i materialnego','afirmacje.pl'),
(597, 'Wybieram trzeźwe i przytomne postrzeganie moich możliwości, wypływających z mojego związku z Bogiem','afirmacje.pl'),
(598, 'Wybieram trzeźwe i przytomne postrzeganie moich relacji z innymi ludźmi','afirmacje.pl'),
(599, 'Wybieram trzeźwe i przytomne postrzeganie siebie i innych ludzi','afirmacje.pl'),
(600, 'Wybieram trzeźwe i przytomne postrzeganie swoich walorów i możliwości','afirmacje.pl'),
(601, 'Wybieram trzeźwe i przytomne postrzeganie swojego miejsca w świecie','afirmacje.pl'),
(602, 'Wybieram trzeźwe i przytomne postrzeganie swojej roli w życiu - sensu mojego życia','afirmacje.pl'),
(603, 'Wybieram trzeźwe i przytomne życie na wszystkich jego poziomach i płaszczyznach','afirmacje.pl'),
(604, 'Wybieram twórczą postawę w życiu, która przynosi mi radość, żywotność i energię','afirmacje.pl'),
(605, 'Wybieram życie na trzeźwo i przytomnie','afirmacje.pl'),
(606, 'Wybieram życie w zdrowiu i szczęściu','afirmacje.pl'),
(607, 'Wykorzystuję swoją pomysłowość w celu pomnożenia moich dochodów','afirmacje.pl'),
(608, 'Wytrwale dążę do wymarzonego celu i akceptuję to, że sukces pojawia się w najwłaściwszym czasie','afirmacje.pl'),
(609, 'Właśnie teraz jest moment mojej twórczej mocy, przejawiam to z wdzięcznością','afirmacje.pl'),
(610, 'Właśnie teraz urzeczywistniam piękno, harmonię i grację w moim ciele','afirmacje.pl'),
(611, 'Z Bożą pomocą uwalniam się od denerwowania, stresowania, nakręcania do walki i to jest dla mnie bezpieczne','afirmacje.pl'),
(612, 'Z Bożą pomocą uwalniam się od przymusu zazdroszczenia, porównywania się','afirmacje.pl'),
(613, 'Z Bożą pomocą wszystko jest dla mnie możliwe','afirmacje.pl'),
(614, 'Z bożą pomocą wszystko jest dla mnie możliwe','afirmacje.pl'),
(615, 'Z każdym dniem coraz bardziej wzrasta i rozwija się moje własne dobro i szczęście','afirmacje.pl'),
(616, 'Z każdym dniem i pod każdym względem żyje mi się łatwiej, bo zasługuję na to','afirmacje.pl'),
(617, 'Z każdym dniem jestem coraz bliżej swojej doskonałej sylwetki','afirmacje.pl'),
(618, 'Z każdym dniem jestem szczuplejszy, aż do osiągnięcia mojej doskonałej wagi i sylwetki','afirmacje.pl'),
(619, 'Z każdym dniem, w każdej dziedzinie mojego życia wszystko układa się coraz lepiej, a ja bogacę się na wszystkich poziomach mojego istnienia','afirmacje.pl'),
(620, 'Z miłości i szacunku dla siebie przyjmuję od innych ludzi tylko to, co jest czyste i korzystne dla mnie','afirmacje.pl'),
(621, 'Z natury jestem dobry i niewinny','afirmacje.pl'),
(622, 'Z oceanu obfitości nieustannie płyną do mnie pieniądze','afirmacje.pl'),
(623, 'Z pełnym poczuciem wolności, swobody i niewinności przyjmuję pomoc i wsparcie, to dla mnie bezpieczne, korzystne i w porządku','afirmacje.pl'),
(624, 'Z ufnością powierzam Bogu wszelkie sprawy, również realizacje moich twórczych pomysłów','afirmacje.pl'),
(625, 'Z ufnością wkraczam w nieznane, chętnie przyjmując to, co służy mojemu szczęściu','afirmacje.pl'),
(626, 'Z zaufaniem przejawiam miłość w swoim życiu - poprzez moje myśli, słowa i działania','afirmacje.pl'),
(627, 'Z łatwością codziennie wstaję wcześnie rano','afirmacje.pl'),
(628, 'Z łatwością doprowadzam moje plany do szczęśliwego zakończenia','afirmacje.pl'),
(629, 'Z łatwością i bez wysiłku zapamiętuję to wszystko, co jest mi potrzebne do odniesienia sukcesu','afirmacje.pl'),
(630, 'Z łatwością i lekkością przejawiam Miłość w swoim życiu','afirmacje.pl'),
(631, 'Z łatwością i na luzie realizuję wszystkie swoje projekty zawodowe','afirmacje.pl'),
(632, 'Z łatwością i poczuciem bezpieczeństwa wyrażam swoją seksualność','afirmacje.pl'),
(633, 'Z łatwością i przyjemnością zarabiam satysfakcjonującą mnie sumę pieniędzy','afirmacje.pl'),
(634, 'Z łatwością koncentruję się na ważnym dla mnie celu','afirmacje.pl'),
(635, 'Z łatwością osiągam wielkie rzeczy','afirmacje.pl'),
(636, 'Z łatwością podejmuję takie działania które uzdrawiają moje ciało','afirmacje.pl'),
(637, 'Z łatwością przyciągam do siebie pieniądze','afirmacje.pl'),
(638, 'Z łatwością przypominam sobie to, co potrzebne, właśnie wtedy, gdy to jest potrzebne','afirmacje.pl'),
(639, 'Z łatwością przypominam sobie wszystko co jest mi potrzebne w danej chwili','afirmacje.pl'),
(640, 'Z łatwością zdaję wszystkie egzaminy, ponieważ sukces jest moim przeznaczeniem','afirmacje.pl'),
(641, 'Z łatwością znajduję rozwiązanie każdego problemu','afirmacje.pl'),
(642, 'Zachowuję trzeźwość i przytomność w relacji ze sobą i z innymi ludźmi','afirmacje.pl'),
(643, 'Zachowuję trzeźwość umysłu wobec emocji innych ludzi, potrafię przytomnie i jasno odczytywać informacje płynące do mnie','afirmacje.pl'),
(644, 'Zaczynam dostrzegać mój twórczy potencjał i korzyści płynące z jego urzeczywistnienia','afirmacje.pl'),
(645, 'Zamieniam nakręcanie się do walki oraz walkę na miłość w moim sercu i to jest dla mnie bezpieczne i korzystne pod każdym względem','afirmacje.pl'),
(646, 'Zapamiętuję szybko, łatwo i skutecznie cały materiał, który mi się przyda','afirmacje.pl'),
(647, 'Zapraszam dobre, twórcze pomysły do mojego życia, pozwalam sobie na przejawienie ich','afirmacje.pl'),
(648, 'Zarabiam coraz więcej z przyjemnością i łatwością','afirmacje.pl'),
(649, 'Zarabiam pieniądze łatwo, lekko i radośnie','afirmacje.pl'),
(650, 'Zarabiam tyle, że czuję się zaspokojony i spełniony finansowo','afirmacje.pl'),
(651, 'Zarabiam z przyjemnością','afirmacje.pl'),
(652, 'Zasługuję aby moja partnerka wspierała mnie w radości i beztroskiej zabawie','afirmacje.pl'),
(653, 'Zasługuję na całe dobro i obfitość, które codziennie otrzymuję','afirmacje.pl'),
(654, 'Zasługuję na doskonałe zdrowie fizyczne i psychiczne i cieszę się tym','afirmacje.pl'),
(655, 'Zasługuję na doskonały seks z idealną dla mnie osobą','afirmacje.pl'),
(656, 'Zasługuję na komfort i przyjemność, to niewinne i w porządku, kiedy dbam o swoje ciało','afirmacje.pl'),
(657, 'Zasługuję na miłość i szacunek','afirmacje.pl'),
(658, 'Zasługuję na partnerkę, która na przytomnie bawi się ze mną w życiu','afirmacje.pl'),
(659, 'Zasługuję na pełnię przyjemności, zaspokojenia w seksie','afirmacje.pl'),
(660, 'Zasługuję na wszystko, co najlepsze, zasługuję na Miłość','afirmacje.pl'),
(661, 'Zasługuję na zaufanie','afirmacje.pl'),
(662, 'Zasługuję na zdrową, szczupłą i harmonijna sylwetkę','afirmacje.pl'),
(663, 'Zasługuję, by moje najpiękniejsze marzenia dotyczące związku i miłości spełniały się w rzeczywistości','afirmacje.pl'),
(664, 'Zauważam jak doskonale działa u mnie proces samouzdrawiania','afirmacje.pl'),
(665, 'Zauważam realne możliwości uzdrowienia mojego ciała','afirmacje.pl'),
(666, 'Zauważam, że harmonijne, obdarzone radosnym spokojem relacje są dla mnie atrakcyjne','afirmacje.pl'),
(667, 'Zauważam, że jestem czystym, niewinnym, bezpiecznym i szerokim kanałem, poprzez który przepływa i przejawia się Boża Moc - twórcza światłość','afirmacje.pl'),
(668, 'Zauważam, że mam wszelkie cechy i talenty potrzebne do realizacji pracy mojego życia','afirmacje.pl'),
(669, 'Zauważam, że mam wszelkie cechy, talenty i możliwości potrzebne do realizacji pracy mojego życia','afirmacje.pl'),
(670, 'Zauważam, że potrafię zwracać się o pomoc w taki sposób, że inni chętnie mi jej udzielają','afirmacje.pl'),
(671, 'Zauważam, że umiem prosić o pomoc w taki sposób, że inni chętnie mi jej udzielają','afirmacje.pl'),
(672, 'Zawsze dostrajam się do boskich wibracji, bez względu na to, w jakim jestem towarzystwie','afirmacje.pl'),
(673, 'Zawsze i wszędzie jestem w porządku','afirmacje.pl'),
(674, 'Zawsze i wszędzie mam doskonały kontakt z Bogiem','afirmacje.pl'),
(675, 'Zawsze i wszędzie podlegam boskiej opiece i ochronie','afirmacje.pl'),
(676, 'Zawsze i wszędzie szczęście mi sprzyja','afirmacje.pl'),
(677, 'Zawsze jestem cenny i wartościowy niezależnie od efektów tego, co robię','afirmacje.pl'),
(678, 'Zawsze jestem chciany, kochany i akceptowany przez ludzi pełnych ciepła i miłości','afirmacje.pl'),
(679, 'Zawsze jestem doskonale przygotowany do każdego egzaminu','afirmacje.pl'),
(680, 'Zawsze jestem na właściwym miejscu o właściwym czasie i z powodzeniem zajmuję się właściwą sprawą','afirmacje.pl'),
(681, 'Zawsze jestem pełen ochoty i zapału do nauki, bo to lubię i wiem, że to jest dla mnie dobre','afirmacje.pl'),
(682, 'Zawsze mam do zaoferowania cenne pomysły, dobra i usługi','afirmacje.pl'),
(683, 'Zawsze mam doskonałe pomysły i z łatwością je realizuję','afirmacje.pl'),
(684, 'Zawsze mam dostatecznie dużo entuzjazmu i konsekwencji by zrealizować ważne dla mnie cele','afirmacje.pl'),
(685, 'Zawsze mam nadmiar swoich własnych pieniędzy','afirmacje.pl'),
(686, 'Zawsze mam nadmiar swojej energii życiowej','afirmacje.pl'),
(687, 'Zawsze mam pomysły, które są godne przejawienia, dlatego zarabiam na nich z łatwością','afirmacje.pl'),
(688, 'Zawsze mam pomysły, które są realne do zrealizowania i harmonizują z najwyższym dobrem','afirmacje.pl'),
(689, 'Zawsze mam powody do radości','afirmacje.pl'),
(690, 'Zawsze mam powody do zadowolenia z efektów mojej pracy','afirmacje.pl'),
(691, 'Zawsze mam radosne i harmonijne relacje ze współrealizatorami moich wspaniałych pomysłów','afirmacje.pl'),
(692, 'Zawsze mam takich klientów, którzy chętnie płacą mi za to, co im oferuję','afirmacje.pl'),
(693, 'Zawsze mam wszystko czego potrzebuję','afirmacje.pl'),
(694, 'Zawsze mam wystarczająco dużo czasu i możliwości na przejawianie moich marzeń','afirmacje.pl'),
(695, 'Zawsze mam wystarczająco dużo pieniędzy na wszystko, czego tylko zapragnę','afirmacje.pl'),
(696, 'Zawsze na czas mam twórcze pomysły i podejmuję właściwe decyzje związane z nimi','afirmacje.pl'),
(697, 'Zawsze potrafię być przytomny i podejmować decyzje z jasnym umysłem, bez względu na otoczenie','afirmacje.pl'),
(698, 'Zawsze potrafię zarobić satysfakcjonującą mnie sumę pieniędzy, niezależnie od obecnej sytuacji społeczno-gospodarczej w kraju','afirmacje.pl'),
(699, 'Zawsze pracuję w przyjemny i bezpieczny dla mnie sposób','afirmacje.pl'),
(700, 'Zawsze realizuję wszystkie swoje pomysły we właściwy sposób, we właściwym miejscu i czasie','afirmacje.pl'),
(701, 'Zawsze robię to co lubię i na co mam ochotę, doskonale funkcjonuję w materii działając w ten sposób','afirmacje.pl'),
(702, 'Zawsze rozróżniam i znajduję sposoby na spontaniczne i lekkie przejawienie mojego boskiego potencjału','afirmacje.pl'),
(703, 'Zawsze sam wiem, czego chcę i osiągam to z łatwością','afirmacje.pl'),
(704, 'Zawsze słucham mojego wnętrza zanim podejmę działanie','afirmacje.pl'),
(705, 'Zawsze wiem co robić aby osiągnąć swoje cele zgodnie z najwyższym dobrem moim i innych','afirmacje.pl'),
(706, 'Zawsze wiem czego chcę i osiągam to z łatwością i przyjemnością','afirmacje.pl'),
(707, 'Zawsze wiem, czego chcę i osiągam to bez oglądania się na innych','afirmacje.pl'),
(708, 'Zawsze wiem, czego chcę i podejmuję najkorzystniejsze dla mnie decyzje i działania','afirmacje.pl'),
(709, 'Zawsze wiem, czego chcę i wyrażam to w sposób jasny i zrozumiały','afirmacje.pl'),
(710, 'Zawsze wiem, czego chcę i zawsze wiem, o co mi chodzi','afirmacje.pl'),
(711, 'Zawsze zachowuję spokój i przytomność umysłu, nawet w konfliktowych i stresujących dla mnie sytuacjach','afirmacje.pl'),
(712, 'Zawsze znajduję najwłaściwsze słowa właśnie wtedy, gdy to jest potrzebne','afirmacje.pl'),
(713, 'Zawsze znajduję rozwiązania gwarantujące mi sukces zgodny z najwyższym dobrem','afirmacje.pl'),
(714, 'Zawsze znajduję sposób na wyrażenie moich niekonwencjonalnych pomysłów, które wspaniale sprawdzają się w życiu','afirmacje.pl'),
(715, 'Zawsze znam właściwe odpowiedzi na pytania, które mi zadają','afirmacje.pl'),
(716, 'Zdrowie jest naturalnym stanem mojego ciała i umysłu','afirmacje.pl'),
(717, 'Ziemskie życie i energia sprzyjają mi, więc pozwalam sobie z tego korzystać','afirmacje.pl'),
(718, 'Znam cel swojego życia','afirmacje.pl'),
(719, 'Znam istotę pracy mojego życia, wiem coraz precyzyjniej jak przejawiać ją w moim życiu','afirmacje.pl'),
(720, 'Znam swoją prawdziwą, boską wartość','afirmacje.pl'),
(721, 'Zwalniam się z funkcji, które sobie narzuciłem','afirmacje.pl'),
(722, 'Łatwo i lekko, dla mojego najwyższego dobra tworzę to, czego chcę','afirmacje.pl'),
(723, 'Świat jest dla mnie dobrym, bezpiecznym, ciekawym i przyjaznym miejscem','afirmacje.pl'),
(724, 'Świat jest dla mnie obfitym miejscem przepełnionym miłością','afirmacje.pl'),
(725, 'Świat stoi przede mną otworem, z Bożą pomocą mam pełnię możliwości do osiągnięcia nawet spektakularnego sukcesu','afirmacje.pl'),
(726, 'Świat w którym żyję jest boskim światem; mam wspaniałą przestrzeń na realizację swoich marzeń','afirmacje.pl'),
(727, 'Świetnie radzę sobie w życiu, spontanicznie odnajduję skuteczne rozwiązania i osiągam wymarzone cele','afirmacje.pl'),
(728, 'Świetnie się bawię na trzeźwo i przytomnie i jestem przy tym bezpieczny, niewinny i w porządku','afirmacje.pl'),
(729, 'Życie jest po to, aby przejawiać i doświadczać miłości Boga','afirmacje.pl'),
(730, 'Życie w ciele jest dla mnie czystą przyjemnością i błogością','afirmacje.pl'),
(731, 'Żyję i tworzę dla własnej radości i przyjemności','afirmacje.pl'),
(732, 'Żyję na luzie i pozwalam by moje życie płynęło zgodnie z boskim planem','afirmacje.pl'),
(733, 'Żyję w bogactwie i obfitości, odnosząc coraz większe sukcesy','afirmacje.pl'),
(734, 'Żyję w bogatym świecie i zawsze mam wszystko, czego potrzebuję do realizacji swoich marzeń','afirmacje.pl'),
(735, 'Żyję w jedności z boskimi wyobrażeniami o mnie, o moich celach i o moich działaniach','afirmacje.pl'),
(736, 'Żyję w jedności z miłością','afirmacje.pl'),
(737, 'Żyję w luksusie i czuję się z tym dobrze','afirmacje.pl');
